/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

import com.sun.rowset.JdbcRowSetImpl;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author k00223361 Vincent Lee
 */
public class AgentDetailsFrame extends javax.swing.JFrame {
    
    JdbcRowSetImpl rowSet = new JdbcRowSetImpl();
    ResultSet resultSet;
    Connection connection;
    Statement statement;
    
    private String agentID;
    private String name;
    private String phone;
    private String fax;
    private String username;
    private String email;
    
    
    /**
     * Creates new form AgentDetailsFrame
     */
    public AgentDetailsFrame(String id) {
        initComponents();
        
        try{
            
        agentUsernameInput.setText(id);
        
        connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/litrealty", "root", "root");
        statement = connection.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,
                                  ResultSet.CONCUR_UPDATABLE);
        //String agentsQuery = "SELECT * FROM litrealty.agents;";
        
        
        String agentsQuery = rowSet.setCommand("SELECT * FROM agents WHERE agentId =  'id'");     //use this if passing id as parameter
        String agentDisplay = rowSet.getString(id);
        
        resultSet = statement.executeQuery(agentsQuery);

        System.out.println("displaying from \'AGENTS\' Table\n");
        
        /*
        while(resultSet.next()) { //shouldn't use while loop, as it goes through ALL the agents. Should only be agent ID from comboBox
            loadAgentRecord();    
        }    
        */    
        }//end try
         catch(Exception sqlex){
            System.err.println("Error in listing agent details");
            System.exit(0);
        }//end catch
        
        
        
    
    } //end agents frame


    
    public void loadAgentRecord() {
        try {
            agentID = resultSet.getString("agentId"); // can also use  '= resultSet.getString("FirstName")' as shorthand
            name = resultSet.getString("name");
            phone = resultSet.getString("phone");
            fax = resultSet.getString("fax");
            username = resultSet.getString("username");
            email = resultSet.getString("email");

            
            
            String filename = this.resultSet.getString("agentImage");
            ImageIcon icon = new ImageIcon(".\\images\\" + filename);
            agentImageLabel.setIcon(icon);
        }
        catch(Exception ex) {
            JOptionPane.showMessageDialog(null, "ERROR " + ex);
        }
        
    }//end load record
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agentDetailsPanel = new javax.swing.JPanel();
        agentIDLabel = new javax.swing.JLabel();
        agentIDInput = new javax.swing.JTextField();
        agentNameLabel = new javax.swing.JLabel();
        agentNameInput = new javax.swing.JTextField();
        agentPhoneLabel = new javax.swing.JLabel();
        agentPhoneInput = new javax.swing.JTextField();
        agentFaxLabel = new javax.swing.JLabel();
        agentFaxInput = new javax.swing.JTextField();
        agentUsernameLabel = new javax.swing.JLabel();
        agentUsernameInput = new javax.swing.JTextField();
        agentEmailLabel = new javax.swing.JLabel();
        agentEmailInput = new javax.swing.JTextField();
        agentImagePanel = new javax.swing.JPanel();
        agentImageLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        goBackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agent Details");
        setMinimumSize(new java.awt.Dimension(300, 300));
        getContentPane().setLayout(new java.awt.BorderLayout(5, 0));

        agentDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Agent Details"));
        agentDetailsPanel.setMinimumSize(new java.awt.Dimension(360, 305));
        agentDetailsPanel.setPreferredSize(new java.awt.Dimension(360, 150));
        agentDetailsPanel.setLayout(new java.awt.GridLayout(6, 2));

        agentIDLabel.setText("Agent ID");
        agentDetailsPanel.add(agentIDLabel);

        agentIDInput.setEditable(false);
        agentIDInput.setText("XXXXXXXXX");
        agentIDInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agentIDInputActionPerformed(evt);
            }
        });
        agentDetailsPanel.add(agentIDInput);

        agentNameLabel.setText("Name");
        agentDetailsPanel.add(agentNameLabel);

        agentNameInput.setEditable(false);
        agentNameInput.setText("XXXXXXXXX");
        agentDetailsPanel.add(agentNameInput);

        agentPhoneLabel.setText("Phone");
        agentDetailsPanel.add(agentPhoneLabel);

        agentPhoneInput.setEditable(false);
        agentPhoneInput.setText("XXXXXXXXX");
        agentDetailsPanel.add(agentPhoneInput);

        agentFaxLabel.setText("Fax");
        agentDetailsPanel.add(agentFaxLabel);

        agentFaxInput.setEditable(false);
        agentFaxInput.setText("XXXXXXXXX");
        agentDetailsPanel.add(agentFaxInput);

        agentUsernameLabel.setText("UserName");
        agentDetailsPanel.add(agentUsernameLabel);

        agentUsernameInput.setEditable(false);
        agentUsernameInput.setText("XXXXXXXXX");
        agentDetailsPanel.add(agentUsernameInput);

        agentEmailLabel.setText("Email");
        agentDetailsPanel.add(agentEmailLabel);

        agentEmailInput.setEditable(false);
        agentEmailInput.setText("XXXXXXXXX");
        agentDetailsPanel.add(agentEmailInput);

        getContentPane().add(agentDetailsPanel, java.awt.BorderLayout.CENTER);

        agentImagePanel.setLayout(new java.awt.BorderLayout());

        agentImageLabel.setIcon(new javax.swing.ImageIcon(".\\images\\noimage.jpg"));
        agentImagePanel.add(agentImageLabel, java.awt.BorderLayout.CENTER);

        getContentPane().add(agentImagePanel, java.awt.BorderLayout.EAST);

        goBackButton.setText("Go Back");
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(goBackButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed
      this.dispose();
    }//GEN-LAST:event_goBackButtonActionPerformed

    private void agentIDInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agentIDInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agentIDInputActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AgentDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AgentDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AgentDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AgentDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AgentDetailsFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel agentDetailsPanel;
    private javax.swing.JTextField agentEmailInput;
    private javax.swing.JLabel agentEmailLabel;
    private javax.swing.JTextField agentFaxInput;
    private javax.swing.JLabel agentFaxLabel;
    private javax.swing.JTextField agentIDInput;
    private javax.swing.JLabel agentIDLabel;
    private javax.swing.JLabel agentImageLabel;
    private javax.swing.JPanel agentImagePanel;
    private javax.swing.JTextField agentNameInput;
    private javax.swing.JLabel agentNameLabel;
    private javax.swing.JTextField agentPhoneInput;
    private javax.swing.JLabel agentPhoneLabel;
    private javax.swing.JTextField agentUsernameInput;
    private javax.swing.JLabel agentUsernameLabel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton goBackButton;
    // End of variables declaration//GEN-END:variables
}
