/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src.view;

import com.sun.rowset.JdbcRowSetImpl;
import java.awt.Color;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import src.db.DBConnection;

/**
 *
 * @author Alan.Ryan
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    JdbcRowSetImpl rowSet;
    ResultSet resultSet;


    public Main() {
        initComponents();

        DBConnection.doConnection();

        rowSet = DBConnection.getAllRecords();

        try {
            if (rowSet.next()) {
                loadRecord();
            } //end if
            else {
                JOptionPane.showMessageDialog(null, "There are no records in the database");
            } //end else
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
            System.exit(0);
        }

    }

    public void loadRecord() {

        try {
            
            double sharesTradedYest = rowSet.getDouble("Shares_Traded_Yesterday");
            
            if (sharesTradedYest < 10)
                companyNameTF.setForeground(Color.red);
            else
                 companyNameTF.setForeground(Color.black);
                
            String cName = rowSet.getString("Company");
            companyNameTF.setText(cName);

            double currentPrice = rowSet.getDouble("Current_Price");
            currentPriceTF.setText(String.valueOf(currentPrice));
            
            double ydayPrice = rowSet.getDouble("Yesterdays_Price");
            yesterdaysPriceTF.setText(String.valueOf(ydayPrice));
            
            
            sharesTradedYesterdayTF.setText(String.valueOf(sharesTradedYest));
            
            double yearlyLow = rowSet.getDouble("Yearly_Low");
            yearlyLowTF.setText(String.valueOf(yearlyLow));
            
            double yearlyHigh = rowSet.getDouble("Yearly_High");
            yearlyHighTF.setText(String.valueOf(yearlyHigh));
            
            Date listingDate = rowSet.getDate("Listing_Date");
            listingDateTF.setText(listingDate.toString());
            
            String file = rowSet.getString("Image");
            ImageIcon icon = new ImageIcon(".\\imgs\\" + file);
            imgLbl.setIcon(icon);
                    

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "ERROR " + ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        companiesDetailsPanel = new javax.swing.JPanel();
        companyNameLbl = new javax.swing.JLabel();
        companyNameTF = new javax.swing.JTextField();
        currentPriceLbl = new javax.swing.JLabel();
        currentPriceTF = new javax.swing.JTextField();
        yesterdaysPriceLbl = new javax.swing.JLabel();
        yesterdaysPriceTF = new javax.swing.JTextField();
        sharesTradedYesterdayLbl = new javax.swing.JLabel();
        sharesTradedYesterdayTF = new javax.swing.JTextField();
        yearlyLowLbl = new javax.swing.JLabel();
        yearlyLowTF = new javax.swing.JTextField();
        yearlyHighLbl = new javax.swing.JLabel();
        yearlyHighTF = new javax.swing.JTextField();
        listingDateLbl = new javax.swing.JLabel();
        listingDateTF = new javax.swing.JTextField();
        controlPanel = new javax.swing.JPanel();
        firstButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();
        lastButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        imgLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ISEQ Application");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        companiesDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Companies List"));
        companiesDetailsPanel.setLayout(new java.awt.GridLayout(7, 2, 20, 20));

        companyNameLbl.setText("Company Name");
        companiesDetailsPanel.add(companyNameLbl);

        companyNameTF.setEditable(false);
        companiesDetailsPanel.add(companyNameTF);

        currentPriceLbl.setText("Current Price");
        companiesDetailsPanel.add(currentPriceLbl);

        currentPriceTF.setEditable(false);
        companiesDetailsPanel.add(currentPriceTF);

        yesterdaysPriceLbl.setText("Yesterdays Price");
        companiesDetailsPanel.add(yesterdaysPriceLbl);

        yesterdaysPriceTF.setEditable(false);
        companiesDetailsPanel.add(yesterdaysPriceTF);

        sharesTradedYesterdayLbl.setText("Shares Traded Yesterday");
        companiesDetailsPanel.add(sharesTradedYesterdayLbl);

        sharesTradedYesterdayTF.setEditable(false);
        companiesDetailsPanel.add(sharesTradedYesterdayTF);

        yearlyLowLbl.setText("Yearly Low");
        companiesDetailsPanel.add(yearlyLowLbl);

        yearlyLowTF.setEditable(false);
        companiesDetailsPanel.add(yearlyLowTF);

        yearlyHighLbl.setText("Yearly High");
        companiesDetailsPanel.add(yearlyHighLbl);

        yearlyHighTF.setEditable(false);
        companiesDetailsPanel.add(yearlyHighTF);

        listingDateLbl.setText("Listing Date");
        companiesDetailsPanel.add(listingDateLbl);

        listingDateTF.setEditable(false);
        companiesDetailsPanel.add(listingDateTF);

        controlPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Controls"));

        firstButton.setText("First");
        firstButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstButtonActionPerformed(evt);
            }
        });
        controlPanel.add(firstButton);

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        controlPanel.add(nextButton);

        previousButton.setText("Previous");
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });
        controlPanel.add(previousButton);

        lastButton.setText("Last");
        lastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastButtonActionPerformed(evt);
            }
        });
        controlPanel.add(lastButton);

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        controlPanel.add(exitButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(controlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                    .addComponent(companiesDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addComponent(imgLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(companiesDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(imgLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(controlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
       try {
            if (rowSet.next()) {
                loadRecord();
            } //end if
            else {
                JOptionPane.showMessageDialog(null, "There are no records in the database");
            } //end else
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
            System.exit(0);
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
         try {
            if (rowSet.previous()) {
                loadRecord();
            } //end if
            else {
                JOptionPane.showMessageDialog(null, "There are no records in the database");
            } //end else
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
            System.exit(0);
        }
    }//GEN-LAST:event_previousButtonActionPerformed

    private void firstButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstButtonActionPerformed
        try {
            if (rowSet.first()) {
                loadRecord();
            } //end if
            else {
                JOptionPane.showMessageDialog(null, "There are no records in the database");
            } //end else
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
            System.exit(0);
        }
    }//GEN-LAST:event_firstButtonActionPerformed

    private void lastButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastButtonActionPerformed
        try {
            if (rowSet.last()) {
                loadRecord();
            } //end if
            else {
                JOptionPane.showMessageDialog(null, "There are no records in the database");
            } //end else
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
            System.exit(0);
        }
    }//GEN-LAST:event_lastButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
         int choice = JOptionPane.showConfirmDialog(this, "Are You Sure You Want To Exit ","ISEQ DB", JOptionPane.YES_NO_OPTION);
     
        if (choice == JOptionPane.YES_OPTION) {
           DBConnection.closeConnection();
           System.exit(0);
        }
       else {
            //do nothing
        }
    }//GEN-LAST:event_exitButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      DBConnection.closeConnection();
      System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel companiesDetailsPanel;
    private javax.swing.JLabel companyNameLbl;
    private javax.swing.JTextField companyNameTF;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel currentPriceLbl;
    private javax.swing.JTextField currentPriceTF;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton firstButton;
    private javax.swing.JLabel imgLbl;
    private javax.swing.JButton lastButton;
    private javax.swing.JLabel listingDateLbl;
    private javax.swing.JTextField listingDateTF;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton previousButton;
    private javax.swing.JLabel sharesTradedYesterdayLbl;
    private javax.swing.JTextField sharesTradedYesterdayTF;
    private javax.swing.JLabel yearlyHighLbl;
    private javax.swing.JTextField yearlyHighTF;
    private javax.swing.JLabel yearlyLowLbl;
    private javax.swing.JTextField yearlyLowTF;
    private javax.swing.JLabel yesterdaysPriceLbl;
    private javax.swing.JTextField yesterdaysPriceTF;
    // End of variables declaration//GEN-END:variables
}
