
package GUI;

import beans.Agents;
import database.AgentsDB;
import javax.swing.ImageIcon;

/**
 *
 * @author Alan.Ryan
 */
public class AgentDetailsFrame extends javax.swing.JFrame {

    /**
     * Creates new form AgentDetailsFrame
     */
    public AgentDetailsFrame(String selectedUsername) {
        initComponents();
        
        //dispose of this frame if the user closes it
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        //get the agents details from the db - based on the selectedUsername
        Agents a = AgentsDB.getAnAgent(selectedUsername);
        
        //put agents details in GUI
        agentIDInput.setText(a.getAgentID() + "");
        agentNameInput.setText(a.getName());
        agentFaxInput.setText(a.getFax());
        agentPhoneInput.setText(a.getPhone());
        agentEmailInput.setText(a.getEmail());
        agentUsernameInput.setText(a.getUsername());
       
        //create imageicon and  put it in the label
        ImageIcon pic = new ImageIcon(".\\images\\" + a.getAgentImage());
        agentImageIabel.setIcon(pic);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agentDetailsPanel = new javax.swing.JPanel();
        agentIDLabel = new javax.swing.JLabel();
        agentIDInput = new javax.swing.JTextField();
        agentNameLabel = new javax.swing.JLabel();
        agentNameInput = new javax.swing.JTextField();
        agentPhoneLabel = new javax.swing.JLabel();
        agentPhoneInput = new javax.swing.JTextField();
        agentFaxLabel = new javax.swing.JLabel();
        agentFaxInput = new javax.swing.JTextField();
        agentUsernameLabel = new javax.swing.JLabel();
        agentUsernameInput = new javax.swing.JTextField();
        agentEmailLabel = new javax.swing.JLabel();
        agentEmailInput = new javax.swing.JTextField();
        agentImagePanel = new javax.swing.JPanel();
        agentImageIabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        goBackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agent Details");
        setMinimumSize(new java.awt.Dimension(300, 300));
        getContentPane().setLayout(new java.awt.BorderLayout(5, 0));

        agentDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Agent Details"));
        agentDetailsPanel.setMinimumSize(new java.awt.Dimension(360, 305));
        agentDetailsPanel.setPreferredSize(new java.awt.Dimension(360, 150));
        agentDetailsPanel.setLayout(new java.awt.GridLayout(6, 2));

        agentIDLabel.setText("Agent ID");
        agentDetailsPanel.add(agentIDLabel);

        agentIDInput.setEditable(false);
        agentIDInput.setText("XXXXXXXXX");
        agentDetailsPanel.add(agentIDInput);

        agentNameLabel.setText("Name");
        agentDetailsPanel.add(agentNameLabel);

        agentNameInput.setEditable(false);
        agentNameInput.setText("XXXXXXXXX");
        agentDetailsPanel.add(agentNameInput);

        agentPhoneLabel.setText("Phone");
        agentDetailsPanel.add(agentPhoneLabel);

        agentPhoneInput.setEditable(false);
        agentPhoneInput.setText("XXXXXXXXX");
        agentDetailsPanel.add(agentPhoneInput);

        agentFaxLabel.setText("Fax");
        agentDetailsPanel.add(agentFaxLabel);

        agentFaxInput.setEditable(false);
        agentFaxInput.setText("XXXXXXXXX");
        agentDetailsPanel.add(agentFaxInput);

        agentUsernameLabel.setText("UserName");
        agentDetailsPanel.add(agentUsernameLabel);

        agentUsernameInput.setEditable(false);
        agentUsernameInput.setText("XXXXXXXXX");
        agentDetailsPanel.add(agentUsernameInput);

        agentEmailLabel.setText("Email");
        agentDetailsPanel.add(agentEmailLabel);

        agentEmailInput.setEditable(false);
        agentEmailInput.setText("XXXXXXXXX");
        agentDetailsPanel.add(agentEmailInput);

        getContentPane().add(agentDetailsPanel, java.awt.BorderLayout.CENTER);

        agentImagePanel.setLayout(new java.awt.BorderLayout());

        agentImageIabel.setIcon(new javax.swing.ImageIcon(".\\images\\noimage.jpg"));
        agentImagePanel.add(agentImageIabel, java.awt.BorderLayout.CENTER);

        getContentPane().add(agentImagePanel, java.awt.BorderLayout.EAST);

        goBackButton.setText("Go Back");
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(goBackButton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed
        //dispose of the frame if the user goes back to the main frame
        this.dispose();
    }//GEN-LAST:event_goBackButtonActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel agentDetailsPanel;
    private javax.swing.JTextField agentEmailInput;
    private javax.swing.JLabel agentEmailLabel;
    private javax.swing.JTextField agentFaxInput;
    private javax.swing.JLabel agentFaxLabel;
    private javax.swing.JTextField agentIDInput;
    private javax.swing.JLabel agentIDLabel;
    private javax.swing.JLabel agentImageIabel;
    private javax.swing.JPanel agentImagePanel;
    private javax.swing.JTextField agentNameInput;
    private javax.swing.JLabel agentNameLabel;
    private javax.swing.JTextField agentPhoneInput;
    private javax.swing.JLabel agentPhoneLabel;
    private javax.swing.JTextField agentUsernameInput;
    private javax.swing.JLabel agentUsernameLabel;
    private javax.swing.JButton goBackButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
