/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ex05companies;

import com.sun.rowset.JdbcRowSetImpl;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import static javax.swing.JOptionPane.QUESTION_MESSAGE;
import javax.swing.JTextArea;
import javax.swing.JComboBox;
import java.sql.*;
/**
 *
 * @author k00223361
 * VINCENT LEE
 */
    


public class companiesGUI extends javax.swing.JFrame {
    JdbcRowSetImpl rowSet = new JdbcRowSetImpl();
    Connection connection; 
    /**
     * Creates new form companiesGUI
     */
    public companiesGUI() {
        initComponents();
        
        try {
            rowSet.setUrl("jdbc:mysql://localhost:3306/iseq"); // 3306 on LIT localost
            rowSet.setUsername("root");
            rowSet.setPassword("root");
       
            String initQuery = "SELECT * FROM prices";
            rowSet.setCommand(initQuery);
            rowSet.execute(); 
            System.out.println("connection established at " + connection);
            System.out.println("displaying from \'PRICES\' Table\n");     
            
            //load from records
            /*
            while(rowSet.next()) {
                String thing = rowSet.getString(1);  //gets the value from agentID column 
                System.out.print("thingy" + thing + "\t");

            }//end while
            */
        }//end try
        catch(SQLException sqlex) {
            JOptionPane.showMessageDialog(null, sqlex.toString(), "Connection Error", JOptionPane.ERROR_MESSAGE);
            System.err.println("SQLException: "+ sqlex.getMessage());
            //sqlex.printStackTrace();
            System.exit(0);
        }
        
        
    }
    
    public void loadRecord() {
        
        try  {
            String compName = rowSet.getObject(1).toString();
            String currentPrice = rowSet.getObject(2).toString();
            String yestPrice = rowSet.getObject(3).toString();
            //double currentPrice = Double.parseDouble(rowSet.getObject(2).toString());
            //double yestPrice = Double.parseDouble(rowSet.getObject(3).toString());

            compName_txtField.setText(compName);
            currentPrice_txtField.setText(currentPrice);
            currentPrice_txtField.setText(yestPrice);    
        }
        catch(SQLException ex) {
            JOptionPane.showMessageDialog(null, "ERROR " + ex);
        }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        compName_txtField = new javax.swing.JTextField();
        currentPrice_txtField = new javax.swing.JTextField();
        yesterPrice_txtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        yesterSharese_txtField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        yearLow_txtField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        yearHigh_txtField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        listDate_txtField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        first_Btn = new javax.swing.JButton();
        next_Btn = new javax.swing.JButton();
        prev_Btn = new javax.swing.JButton();
        last_Btn = new javax.swing.JButton();
        exit_Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Company Name");

        jLabel2.setText("Current Price");

        jLabel3.setText("Yesterdays Price");

        compName_txtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compName_txtFieldActionPerformed(evt);
            }
        });

        currentPrice_txtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentPrice_txtFieldActionPerformed(evt);
            }
        });

        yesterPrice_txtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesterPrice_txtFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Shares Traded Yesterday");

        yesterSharese_txtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesterSharese_txtFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Yearly Low");

        yearLow_txtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearLow_txtFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Yearly High");

        yearHigh_txtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearHigh_txtFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Listing Date");

        listDate_txtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listDate_txtFieldActionPerformed(evt);
            }
        });

        first_Btn.setText("First");
        first_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                first_BtnActionPerformed(evt);
            }
        });

        next_Btn.setText("Next");
        next_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next_BtnActionPerformed(evt);
            }
        });

        prev_Btn.setText("Next");
        prev_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prev_BtnActionPerformed(evt);
            }
        });

        last_Btn.setText("Next");
        last_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                last_BtnActionPerformed(evt);
            }
        });

        exit_Btn.setText("EXIT");
        exit_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listDate_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearHigh_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearLow_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yesterSharese_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yesterPrice_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(currentPrice_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(compName_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(first_Btn)
                                .addGap(18, 18, 18)
                                .addComponent(next_Btn)
                                .addGap(18, 18, 18)
                                .addComponent(prev_Btn)
                                .addGap(18, 18, 18)
                                .addComponent(last_Btn)
                                .addGap(18, 18, 18)
                                .addComponent(exit_Btn))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(236, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(compName_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(currentPrice_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(yesterPrice_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(yesterSharese_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(yearLow_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(yearHigh_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(listDate_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(first_Btn)
                    .addComponent(next_Btn)
                    .addComponent(prev_Btn)
                    .addComponent(last_Btn)
                    .addComponent(exit_Btn))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void compName_txtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compName_txtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compName_txtFieldActionPerformed

    private void currentPrice_txtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentPrice_txtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentPrice_txtFieldActionPerformed

    private void yesterPrice_txtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesterPrice_txtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yesterPrice_txtFieldActionPerformed

    private void yesterSharese_txtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesterSharese_txtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yesterSharese_txtFieldActionPerformed

    private void yearLow_txtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearLow_txtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearLow_txtFieldActionPerformed

    private void yearHigh_txtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearHigh_txtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearHigh_txtFieldActionPerformed

    private void listDate_txtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listDate_txtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listDate_txtFieldActionPerformed

    private void first_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_first_BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_first_BtnActionPerformed

    private void next_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next_BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_next_BtnActionPerformed

    private void prev_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prev_BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prev_BtnActionPerformed

    private void last_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_last_BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_last_BtnActionPerformed

    private void exit_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_BtnActionPerformed
        // EXIT
        System.exit(0);
        
    }//GEN-LAST:event_exit_BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(companiesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(companiesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(companiesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(companiesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new companiesGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField compName_txtField;
    private javax.swing.JTextField currentPrice_txtField;
    private javax.swing.JButton exit_Btn;
    private javax.swing.JButton first_Btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton last_Btn;
    private javax.swing.JTextField listDate_txtField;
    private javax.swing.JButton next_Btn;
    private javax.swing.JButton prev_Btn;
    private javax.swing.JTextField yearHigh_txtField;
    private javax.swing.JTextField yearLow_txtField;
    private javax.swing.JTextField yesterPrice_txtField;
    private javax.swing.JTextField yesterSharese_txtField;
    // End of variables declaration//GEN-END:variables
}
