/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab01_currencyconverter;

import java.io.IOException;
import java.text.NumberFormat;
import java.util.Calendar;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author DragonDream
 */
public class CurrencyConvertFrame extends javax.swing.JFrame {
    
    /**
     * Creates new form CurrencyConvertFrame
     */
    String language = "ENGLISH";
    String country = "USA";
    
    Locale locale = new Locale(language, country); //create locale object
    Locale usa = new Locale("en", "US"); //create USA locale object for 'amount'

    Locale canada = new Locale("en", "CA"); //create Canada locale object
    Locale france = new Locale("fr", "FR"); //create Thailand locale object for 'amount'
    Locale thailand = new Locale("th", "TH"); //create Thailand locale object for 'amount'
    Locale britain = new Locale("en", "EN"); //create great Britain locale object for 'amount'


    
    Locale locales[] = Calendar.getAvailableLocales(); //array of all locales
    
    double amount = 0; 
    double canDollars = 0;
    double franEuro = 0;
    double thaiBaht = 0;
    double britPounds = 0;
    
    double canDollarsConverted = 0;
    double franEuroConverted = 0;
    double thaiBahtConverted = 0;
    double britPoundsConverted = 0;
    
    
    
    public CurrencyConvertFrame() {
        initComponents();
        setLabels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        entryTextField = new javax.swing.JTextField();
        enterHeaderLabel = new javax.swing.JLabel();
        usDollarsLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        convert_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        canDollarsLabel = new javax.swing.JLabel();
        canDollar_TextField = new javax.swing.JTextField();
        currencyLabel = new javax.swing.JLabel();
        exchangeLabel = new javax.swing.JLabel();
        convertedLabel = new javax.swing.JLabel();
        franEuroTextField = new javax.swing.JTextField();
        franEuroLabel = new javax.swing.JLabel();
        thaiBahtLabel = new javax.swing.JLabel();
        thaiBahtTextField = new javax.swing.JTextField();
        britishPoundsLabel = new javax.swing.JLabel();
        britPoundsTextField = new javax.swing.JTextField();
        canDollarConverted_TextField = new javax.swing.JTextField();
        euroFranceConverted_TextField = new javax.swing.JTextField();
        thatBahtConverted_TextField = new javax.swing.JTextField();
        britishPoundsConverted_TextField = new javax.swing.JTextField();
        exchangeSectionHeaderLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        entryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryTextFieldActionPerformed(evt);
            }
        });
        entryTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                entryTextFieldKeyTyped(evt);
            }
        });

        enterHeaderLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        enterHeaderLabel.setText("Enter Dollar Amount");

        usDollarsLabel.setText("US Dollars");

        convert_btn.setText("Convert");
        convert_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convert_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(enterHeaderLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(usDollarsLabel)
                                .addGap(38, 38, 38)
                                .addComponent(entryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(convert_btn)
                                .addGap(79, 79, 79)))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enterHeaderLabel)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usDollarsLabel)
                    .addComponent(entryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(convert_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        canDollarsLabel.setText("Canadian Dollars");

        canDollar_TextField.setEditable(false);
        canDollar_TextField.setText("1.2");
        canDollar_TextField.setEnabled(false);

        currencyLabel.setText("CURRENCY");

        exchangeLabel.setText("EXCHANGE RATES");

        convertedLabel.setText("CONVERTED AMOUNT");

        franEuroTextField.setEditable(false);
        franEuroTextField.setText("0.73");
        franEuroTextField.setEnabled(false);

        franEuroLabel.setText("Euro (France)");

        thaiBahtLabel.setText("Thai BAHT");

        thaiBahtTextField.setEditable(false);
        thaiBahtTextField.setText("30.99");
        thaiBahtTextField.setEnabled(false);

        britishPoundsLabel.setText("British Pounds");

        britPoundsTextField.setEditable(false);
        britPoundsTextField.setText("0.63");
        britPoundsTextField.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(canDollarsLabel)
                    .addComponent(currencyLabel)
                    .addComponent(franEuroLabel)
                    .addComponent(thaiBahtLabel)
                    .addComponent(britishPoundsLabel))
                .addGap(79, 79, 79)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exchangeLabel)
                    .addComponent(canDollar_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(franEuroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thaiBahtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(britPoundsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(britishPoundsConverted_TextField)
                    .addComponent(thatBahtConverted_TextField)
                    .addComponent(euroFranceConverted_TextField)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(convertedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(canDollarConverted_TextField)))
                .addGap(0, 50, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currencyLabel)
                    .addComponent(exchangeLabel)
                    .addComponent(convertedLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(canDollarsLabel)
                    .addComponent(canDollar_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(canDollarConverted_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(franEuroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(franEuroLabel)
                    .addComponent(euroFranceConverted_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thaiBahtLabel)
                    .addComponent(thaiBahtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thatBahtConverted_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(britishPoundsLabel)
                    .addComponent(britPoundsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(britishPoundsConverted_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        exchangeSectionHeaderLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        exchangeSectionHeaderLabel.setText("Exchange Rates");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exchangeSectionHeaderLabel)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exchangeSectionHeaderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void convert_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convert_btnActionPerformed
        // Press CONVERT button
        
        try{
            amount = Double.parseDouble( entryTextField.getText() );
            canDollarsConverted = amount*1.02;
            franEuroConverted = amount*0.73;
            thaiBahtConverted = amount*30.99;
            britPoundsConverted = amount*0.63;
            setLabels();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Input has to be a number : " + e.getMessage());
        }
    }//GEN-LAST:event_convert_btnActionPerformed

    private void entryTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_entryTextFieldKeyTyped
        // Event handler to make sure text entered is number
        
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        
        }
        
    }//GEN-LAST:event_entryTextFieldKeyTyped

    private void entryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CurrencyConvertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CurrencyConvertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CurrencyConvertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CurrencyConvertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CurrencyConvertFrame().setVisible(true);
            }
        });
    }//end main
    
    public void setLabels() {
    	NumberFormat canadaCurrencyFormat = NumberFormat.getCurrencyInstance(canada);
        NumberFormat franceCurrencyFormat = NumberFormat.getCurrencyInstance(france);
        NumberFormat thailandCurrencyFormat = NumberFormat.getCurrencyInstance(thailand);
        NumberFormat britainCurrencyFormat = NumberFormat.getCurrencyInstance(britain);

    	canDollarConverted_TextField.setText( canadaCurrencyFormat.format(canDollarsConverted) );
        euroFranceConverted_TextField.setText( franceCurrencyFormat.format(franEuroConverted) );
        thatBahtConverted_TextField.setText( thailandCurrencyFormat.format(thaiBahtConverted) );
        britishPoundsConverted_TextField.setText( britainCurrencyFormat.format(britPoundsConverted) );
        

    }// end setLabels
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField britPoundsTextField;
    private javax.swing.JTextField britishPoundsConverted_TextField;
    private javax.swing.JLabel britishPoundsLabel;
    private javax.swing.JTextField canDollarConverted_TextField;
    private javax.swing.JTextField canDollar_TextField;
    private javax.swing.JLabel canDollarsLabel;
    private javax.swing.JButton convert_btn;
    private javax.swing.JLabel convertedLabel;
    private javax.swing.JLabel currencyLabel;
    private javax.swing.JLabel enterHeaderLabel;
    private javax.swing.JTextField entryTextField;
    private javax.swing.JTextField euroFranceConverted_TextField;
    private javax.swing.JLabel exchangeLabel;
    private javax.swing.JLabel exchangeSectionHeaderLabel;
    private javax.swing.JLabel franEuroLabel;
    private javax.swing.JTextField franEuroTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel thaiBahtLabel;
    private javax.swing.JTextField thaiBahtTextField;
    private javax.swing.JTextField thatBahtConverted_TextField;
    private javax.swing.JLabel usDollarsLabel;
    // End of variables declaration//GEN-END:variables
}
