/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

import java.text.DateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Locale;
import javax.swing.JOptionPane;


/**
 *
 * @author alan.ryan
 */
public class LaunchFrame extends javax.swing.JFrame {

    
    
    Locale [] locales = { new Locale("pt", "BR"), new Locale("fr", "CA"), new Locale("de", "DE"), new Locale("ga", "IE"), new Locale("us", "US") };  
    String today; //holds today's date and time in LONG format
    String todayShort; //holds today's date and time in SHORT format
    String output = ""; //for output to JTextArea
    

    /**
     * Creates new form LaunchFrame
     */
    public LaunchFrame() {
        initComponents();
        
        
        // Initialize the combo box to add locale names. Add each of the locales array into the combobox
    	for (int i=0; i<locales.length; i++)
      		localeComboBox.addItem(locales[i].getDisplayName()); //use display name, otherwise you won't make sense of the Country Codes IE, US, CA, PO blah blah bnlah

        localeComboBox.setSelectedItem("Brasil"); //set selected item ... otherwise when it runs Nothing will be in the comboBox
        //NOTE event handler in comboBox from GUI/awt
    }

    public void setLocale() {

        GregorianCalendar calendar = new GregorianCalendar();
        
        formatter = DateFormat.getDateTimeInstance(DateFormat.LONG, DateFormat.MEDIUM, locales); //pass these three arguments into the method. LONG is how the date is displayed, February vs Feb vs 2... Date, Time, Locale 
        //get a calendar with current time, format it, assign it to the String variable to display
        today = formatter.format(calendar.getTime()); 
        
        output += "Selected Country: " + localeComboBox.getSelectedItem(); //get the current selected item in combobox, might use toString()
        
        output += "Full Date: " + today;
        output += "Short Date: " + todayShort;
        output += "\nMONTH: " + calendar.get(Calendar.MONTH, Calendar.SHORT, selectedLocale);
        output += "\nFull Time: " + calendar.get(Calendar.YEAR);
        output += "\nHour of Day: " + calendar.get(Calendar.HOUR_OF_DAY);
        JOptionPane.showMessageDialog(null, output);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        controlPanel = new javax.swing.JPanel();
        selectLocaleLabel = new javax.swing.JLabel();
        localeComboBox = new javax.swing.JComboBox();
        outputPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        output_TextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Working With Dates and Times");

        selectLocaleLabel.setText("Select Locale");
        controlPanel.add(selectLocaleLabel);

        localeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Brazil", "Canada", "Germany", "Ireland", "United States" }));
        localeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localeComboBoxActionPerformed(evt);
            }
        });
        controlPanel.add(localeComboBox);

        getContentPane().add(controlPanel, java.awt.BorderLayout.NORTH);

        outputPanel.setLayout(new java.awt.BorderLayout());

        output_TextArea.setColumns(20);
        output_TextArea.setRows(5);
        jScrollPane1.setViewportView(output_TextArea);

        outputPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(outputPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void localeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localeComboBoxActionPerformed
        // TODO add your handling code here:
        setLocale(); //gets current date and time from computer
        
    }//GEN-LAST:event_localeComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaunchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaunchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaunchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaunchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new LaunchFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel controlPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox localeComboBox;
    private javax.swing.JPanel outputPanel;
    private javax.swing.JTextArea output_TextArea;
    private javax.swing.JLabel selectLocaleLabel;
    // End of variables declaration//GEN-END:variables
}
